name: CI/CD to Docker Hub

on: [push]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t docker.io/rahat6/spring-boot-k8s:latest .
          docker tag docker.io/rahat6/spring-boot-k8s:latest docker.io/rahat6/spring-boot-k8s:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rahat6
          password: ${{ secrets.GHCR_PAT }}

      - name: Push to Docker Hub
        run: |
          docker push docker.io/rahat6/spring-boot-k8s:latest
          docker push docker.io/rahat6/spring-boot-k8s:${{ github.sha }}
